spring:
  application:
    name: cardappio-test
#  profiles:
#   active: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cardappio
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

AWS_ACCESS: test-access-key
AWS_SECRET: test-secret-key
AWS_BUCKET: test-bucket

abacatepay:
  api:
    key: TEST_ABACATE_PAY_KEY
    base-url: https://api.abacatepay.com/v1
    webhook:
      url: http://localhost:8080/api/webhooks/abacatepay
      secret: TEST_ABACATE_PAY_WEBHOOK_SECRET
    return-url: http://localhost:4200/checkout/cancel
    completion-url: http://localhost:4200/checkout/success

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri:
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
#      - org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration
#  keycloak:
#    enabled: false
#  cors:
#    allowed-origins:
#      - "http://localhost:4200"
#    allowed-methods:
#      - GET
#      - POST
#      - PUT
#      - DELETE
#    allowed-headers:
#      - "*"