spring:
  application:
    name: cardappio-prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak-cardappio.up.railway.app/realms/cardappio-app

keycloak:
  realm: cardappio-app
  auth-server-url: https://keycloak-cardappio.up.railway.app
  resource: frontend-app
  credentials:
    secret: XA3HrCWwLYOtdZ50buEVE9ZwxECw8zCY
    public-client: false
  bearer-only: true
  ssl-required: external

abacatepay:
  api:
    key: ${ABACATEPAY_API_KEY:DEFAULT_ABACATE_PAY_KEY}
    base-url: ${ABACATEPAY_API_BASE_URL:https://api.abacatepay.com/v1}
    webhook:
      url: ${ABACATEPAY_API_WEBHOOK_URL:https://cardappio-prod.up.railway.app/api/webhooks/abacatepay}
      secret: ${ABACATEPAY_API_WEBHOOK_SECRET:DEFAULT_ABACATE_PAY_WEBHOOK_SECRET}