spring:
  application:
    name: cardappio-dev
  flyway:
    logging:
      level:
        org.flywaydb: DEBUG
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cardappio
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


AWS_ACCESS: any
AWS_SECRET: any
AWS_BUCKET: any